name: Build Modpack

on:
  pull_request:
  push:
    branches:
      - main  # Change this to your preferred branch
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'  # Change to '8' for Java 8

      - name: Install 7z
        uses: milliewalky/setup-7-zip@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Update Packwiz
        run: make update-packwiz

      - name: Make Pre-Build Cleanup
        run: make preClean

      - name: Make Modpack
        run: make multimc curseforge modrinth # Change this to your desired build targets

      - name: Make Post-Build Cleanup
        run: make postClean

      - name: Make Modlist
        run: make release-file

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modpack-build
          path: .build/